name: Generate issues with TODO-or-not

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - dev/staging
  push:
    branches:
      - dev/staging
jobs:
  run_todoon:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"
      - name: Install TODO-or-not from the checked-out source
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Generate GH Token for todoon app
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 853479
          private-key: ${{ secrets.TODOON_CLIENT_PEM }}
      - name: Run TODO-or-not in issue mode
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          MAXIMUM_ISSUES_GENERATED: 10
        run: |
          echo "Generate GitHub issues for each problem found, but don't fail the workflow unless one is found that has already been closed."
          todoon -si --github-env
      - name: Run TODO-or-not in check mode for fork PRs
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "Running TODO-or-not in check mode because this is a fork PR and secrets are unavailable."
          todoon --silent
      - name: Check duplicate closed issues
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: |
          if [ "${{ env.TODOON_DUPLICATE_CLOSED_ISSUES }}" != "1" ]; then
            echo "Detected ${{ env.TODOON_DUPLICATE_CLOSED_ISSUES }} duplicate closed issues where we expected exactly one (an example), failing this workflow!"
            exit 1
          fi
